<?php
    print_r($_POST['nome']);
    print_r('<br>');
    print_r($_POST['cpf']);
    print_r('<br>');
    print_r($_POST['telefone']);
    print_r('<br>');
    print_r($_POST['datanascimento']);
    print_r('<br>');
    print_r($_POST['senha']);
    print_r('<br>');