let suggestions = [
    "Quais são os pré-requisitos para este curso?",
    "O curso é adequado para iniciantes ou para quem já tem alguma experiência na área?",
    "Qual a carga horária total do curso?",
    "Quanto tempo tenho para concluir o curso?",
    "O curso é presencial ou online?",
    "Quais são os horários das aulas?",
    "Posso assistir às aulas quantas vezes quiser?",
    "O curso oferece certificado de conclusão?",
    "Qual o valor do curso?",
    "Existem opções de pagamento parcelado?",
    "Há descontos disponíveis?",
    "Como posso me inscrever no curso?",
    "Preciso criar uma conta no site para me inscrever?",
    "Como receberei o acesso ao curso?",
    "Em qual plataforma o curso será disponibilizado?",
    "Posso acessar o curso de qualquer dispositivo?",
    "Preciso ter internet para acessar o curso?",
    "Posso cancelar minha inscrição no curso?",
    "Como posso solicitar reembolso?",
    "Tenho outras dúvidas sobre o curso. Como posso entrar em contato com vocês?",
  ];